openapi: 3.0.3

info:
  title: Uprav API
  version: 1.0.0
  description: Uprav API

servers:
  - url: http://localhost:1124
    description: development server

paths:
  /api/tasks:
    get:
      summary: get all tasks
      tags:
        - Tasks
      operationId: getTasks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TaskResponse"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /api/newtask:
    post:
      summary: create new task
      tags:
        - Tasks
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  responses:
    Accepted:
      description: Accepted
    NoContent:
      description: No Content
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Internal server error
  schemas:
    TaskRequest:
      type: object
      properties:
        uid:
          type: string
          format: uuid
          description: "ユーザーの一意識別子 (uid)"
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          description: "名前"
          example: "タスクのタイトル"
        priority:
          type: integer
          description: "優先度"
          minimum: 1
          maximum: 5
          example: 3
        tag:
          type: string
          description: "ジャンル"
          example: "課題"
        deadline:
          type: string
          format: date-time
          description: "真の締切（ISO8601形式を推奨）"
          example: "2023-12-31T23:59:59Z"
        period:
          type: string
          format: date-time
          description: "目安の締切"
          example: "2023-12-25T18:00:00Z"
        assumption:
          type: array
          items:
            type: string
            format: uuid
          description: "前提タスクのID(複数を指定可能)"
        group:
          type: string
          format: uuid
          description: "タスクグループのID"
        assign:
          type: string
          format: uuid
          description: "担当者のuid"

      # 必須項目がある場合はここに追加します
      # required:
      #   - uid
      #   - name
      #   - priority
      #   - tag
    TaskResponse:
      type: object
      properties:
        id:
          type: integer
          description: "タスクのID"
          example: 1
        uid:
          type: string
          format: uuid
          description: "ユーザーの一意識別子 (uid)"
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          description: "名前"
          example: "タスクのタイトル"
        priority:
          type: integer
          description: "優先度"
          minimum: 1
          maximum: 5
          example: 3
        tag:
          type: string
          description: "ジャンル"
          example: "課題"
        deadline:
          type: string
          format: date-time
          description: "真の締切（ISO8601形式を推奨）"
          example: "2023-12-31T23:59:59Z"
        period:
          type: string
          format: date-time
          description: "目安の締切"
          example: "2023-12-25T18:00:00Z"
        assumption:
          type: array
          items:
            type: string
            format: uuid
          description: "前提タスクのID(複数を指定可能)"
        group:
          type: string
          format: uuid
          description: "タスクグループのID"
        assign:
          type: string
          format: uuid
          description: "担当者のuid"

      # 必須項目がある場合はここに追加します
      # required:
      #   - uid
      #   - name
      #   - priority
      #   - tag
