openapi: 3.0.3

info:
  title: Uprav API
  version: 1.0.0
  description: Uprav API

servers:
  - url: http://localhost:1124
    description: development server

paths:
  #エンドポイント
  /api/me:
    get:
      summary: get current user status (Token validation)
      tags:
        - Authentication
      operationId: getCurrentUser
      security:
        - BearerAuth: [] # トークンが必要であることを明記
      responses:
        "200":
          description: Token is valid. Returns login user info.
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: integer
                    description: "ユーザーのUID"
                    example: 10001
                  name:
                    type: string
                    description: "ユーザーの名前"
                    example: "Mira"
        "401":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /api/tasks:
    get:
      summary: get all tasks
      tags:
        - Tasks
      operationId: getTasks
      security:
        - BearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TaskResponse"
        "500":
          $ref: "#/components/responses/InternalServerError"
          
    post:
      summary: create new task
      tags:
        - Tasks
      operationId: createTask
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewTaskRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/tasks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: タスクのID
        schema:
          type: integer

    get:
      summary: get task
      tags:
        - Tasks
      operationId: getTask
      security:
        - BearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

    put:
      summary: update task
      tags:
        - Tasks
      operationId: updateTask
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTaskRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

    delete:
      summary: delete task
      tags:
        - Tasks
      operationId: deleteTask
      security:
        - BearerAuth: []
      responses:
        "200":
          $ref: "#/components/responses/Accepted"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

  #認証関係
  /api/login:
    post:
      summary: login
      tags:
        - Authentication
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
          
  /api/signup:
    post:
      summary: signup
      tags:
        - Authentication
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  responses:
    Accepted:
      description: Accepted
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    NoContent:
      description: No Content
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Internal server error
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    NewTaskRequest:
      type: object
      properties:
        name:
          type: string
          description: "名前"
          example: "タスクのタイトル"
        priority:
          type: integer
          description: "優先度"
          minimum: 1
          maximum: 5
          example: 3
        tag:
          type: string
          description: "ジャンル"
          example: "課題"
        deadline:
          type: string
          format: date-time
          description: "真の締切（ISO8601形式を推奨）"
          example: "2023-12-31T23:59:59Z"
        period:
          type: string
          format: date-time
          description: "目安の締切"
          example: "2023-12-25T18:00:00Z"
        is_everyday:
          type: boolean
          description: "毎日繰り返すタスクかどうか"
          example: false
        description:
          type: string
          description: "タスクの説明"
          example: "場所は○○○教室、持ち物は△△△"
        group:
          type: string
          format: uuid
          description: "タスクグループのID"
        assign:
          type: string
          format: uuid
          description: "担当者のuid"
      required:
        - name
        - priority
        - deadline
        - is_everyday
    TaskResponse:
      type: object
      properties:
        id:
          type: integer
          description: "タスクのID"
          example: 1
        name:
          type: string
          description: "名前"
          example: "タスクのタイトル"
        priority:
          type: integer
          description: "優先度"
          minimum: 1
          maximum: 5
          example: 3
        tag:
          type: string
          description: "ジャンル"
          example: "課題"
        deadline:
          type: string
          format: date-time
          description: "真の締切（ISO8601形式を推奨）"
          example: "2023-12-31T23:59:59Z"
        period:
          type: string
          format: date-time
          description: "目安の締切"
          example: "2023-12-25T18:00:00Z"
        is_everyday:
          type: boolean
          description: "毎日繰り返すタスクかどうか"
          example: false
        description:
          type: string
          description: "タスクの説明"
          example: "場所は○○○教室、持ち物は△△△"
        group:
          type: string
          format: uuid
          description: "タスクグループのID"
        assign:
          type: string
          format: uuid
          description: "担当者のuid"
      required:
        - name
        - priority
        - deadline
        - is_everyday
    UpdateTaskRequest:
      type: object
      properties:
        name:
          type: string
          description: "名前"
          example: "タスクのタイトル"
        priority:
          type: integer
          description: "優先度"
          minimum: 1
          maximum: 5
          example: 3
        tag:
          type: string
          description: "ジャンル"
          example: "課題"
        deadline:
          type: string
          format: date-time
          description: "真の締切（ISO8601形式を推奨）"
          example: "2023-12-31T23:59:59Z"
        period:
          type: string
          format: date-time
          description: "目安の締切"
          example: "2023-12-25T18:00:00Z"
        is_everyday:
          type: boolean
          description: "毎日繰り返すタスクかどうか"
          example: false
        description:
          type: string
          description: "タスクの説明"
          example: "場所は○○○教室、持ち物は△△△"
        group:
          type: string
          format: uuid
          description: "タスクグループのID"
        assign:
          type: string
          format: uuid
          description: "担当者のuid"
    
    AuthenticationRequest:
      type: object
      properties:
        name:
          type: string
          description: "ユーザーの名前"
          example: "Mira"
        password:
          type: string
          description: "パスワード"
          example: "password123"
      required:
        - name
        - password
    AuthenticationResponse:
      type: object
      properties:
        uid:
          type: integer
          description: "10000から始まるUID"
          example: 10001
        name:
          type: string
          description: "ユーザーの名前"
          example: "Mira"
        token:
          type: string
          description: "JWTトークン"
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."