// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AuthenticationRequest defines model for AuthenticationRequest.
type AuthenticationRequest struct {
	// Name ユーザーの名前
	Name string `json:"name"`

	// Password パスワード
	Password string `json:"password"`
}

// AuthenticationResponse defines model for AuthenticationResponse.
type AuthenticationResponse struct {
	// Name ユーザーの名前
	Name *string `json:"name,omitempty"`

	// Token JWTトークン
	Token *string `json:"token,omitempty"`

	// Uid 10000から始まるUID
	Uid *int `json:"uid,omitempty"`
}

// GroupMember defines model for GroupMember.
type GroupMember struct {
	Name string `json:"name"`
	Uid  int    `json:"uid"`
}

// GroupRequest defines model for GroupRequest.
type GroupRequest struct {
	// Members グループに所属するメンバーのUID
	Members []uint `json:"members"`

	// Name グループ名
	Name string `json:"name"`
}

// GroupResponse defines model for GroupResponse.
type GroupResponse struct {
	// Id グループのID
	Id openapi_types.UUID `json:"id"`

	// Members グループに所属するメンバーの一覧
	Members []GroupMember `json:"members"`

	// Name グループ名
	Name string `json:"name"`
}

// NewTaskRequest defines model for NewTaskRequest.
type NewTaskRequest struct {
	// AssignGroup 担当者のグループ
	AssignGroup *openapi_types.UUID `json:"assignGroup,omitempty"`

	// Assignee 担当者のuid
	Assignee *int `json:"assignee,omitempty"`

	// Deadline 真の締切（ISO8601形式を推奨）
	Deadline time.Time `json:"deadline"`

	// Description タスクの説明
	Description *string `json:"description,omitempty"`

	// Group タスクグループのID
	Group *openapi_types.UUID `json:"group,omitempty"`

	// IsEveryday 毎日繰り返すタスクかどうか
	IsEveryday bool `json:"is_everyday"`

	// Name 名前
	Name string `json:"name"`

	// Period 目安の締切
	Period *time.Time `json:"period,omitempty"`

	// Priority 優先度
	Priority int `json:"priority"`

	// Tag ジャンル
	Tag *string `json:"tag,omitempty"`
}

// TagsResponse defines model for TagsResponse.
type TagsResponse struct {
	// Tags タグのリスト
	Tags *[]string `json:"tags,omitempty"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	// AssignGroup 担当者のグループ
	AssignGroup *string `json:"assignGroup,omitempty"`

	// Assigner 割り当てた者のuid
	Assigner *string `json:"assigner,omitempty"`

	// Deadline 真の締切（ISO8601形式を推奨）
	Deadline time.Time `json:"deadline"`

	// Description タスクの説明
	Description *string `json:"description,omitempty"`

	// Group タスクグループのID
	Group *openapi_types.UUID `json:"group,omitempty"`

	// Id タスクのID
	Id *int `json:"id,omitempty"`

	// IsEveryday 毎日繰り返すタスクかどうか
	IsEveryday bool `json:"is_everyday"`

	// Name 名前
	Name string `json:"name"`

	// Period 目安の締切
	Period *time.Time `json:"period,omitempty"`

	// Priority 優先度
	Priority int `json:"priority"`

	// Tag ジャンル
	Tag *string `json:"tag,omitempty"`
}

// UpdateGroupRequest defines model for UpdateGroupRequest.
type UpdateGroupRequest struct {
	// Members グループに所属するメンバーのUID
	Members []uint `json:"members"`

	// Name グループ名
	Name string `json:"name"`
}

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	// AssignGroup 担当者のグループ
	AssignGroup *openapi_types.UUID `json:"assignGroup,omitempty"`

	// Assignee 担当者のuid
	Assignee *int `json:"assignee,omitempty"`

	// Deadline 真の締切（ISO8601形式を推奨）
	Deadline *time.Time `json:"deadline,omitempty"`

	// Description タスクの説明
	Description *string `json:"description,omitempty"`

	// Group タスクグループのID
	Group *openapi_types.UUID `json:"group,omitempty"`

	// IsEveryday 毎日繰り返すタスクかどうか
	IsEveryday *bool `json:"is_everyday,omitempty"`

	// Name 名前
	Name *string `json:"name,omitempty"`

	// Period 目安の締切
	Period *time.Time `json:"period,omitempty"`

	// Priority 優先度
	Priority *int `json:"priority,omitempty"`

	// Tag ジャンル
	Tag *string `json:"tag,omitempty"`
}

// Accepted defines model for Accepted.
type Accepted struct {
	Message *string `json:"message,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Message *string `json:"message,omitempty"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	Message *string `json:"message,omitempty"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Message *string `json:"message,omitempty"`
}

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = GroupRequest

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = UpdateGroupRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = AuthenticationRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = AuthenticationRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = NewTaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// get all groups
	// (GET /api/groups)
	GetGroups(ctx echo.Context) error
	// create new group
	// (POST /api/groups)
	CreateGroup(ctx echo.Context) error
	// delete group
	// (DELETE /api/groups/{id})
	DeleteGroup(ctx echo.Context, id openapi_types.UUID) error
	// get group
	// (GET /api/groups/{id})
	GetGroup(ctx echo.Context, id openapi_types.UUID) error
	// update group
	// (PUT /api/groups/{id})
	UpdateGroup(ctx echo.Context, id openapi_types.UUID) error
	// login
	// (POST /api/login)
	Login(ctx echo.Context) error
	// get current user status (Token validation)
	// (GET /api/me)
	GetCurrentUser(ctx echo.Context) error
	// signup
	// (POST /api/signup)
	Signup(ctx echo.Context) error
	// get all tasks
	// (GET /api/tasks)
	GetTasks(ctx echo.Context) error
	// create new task
	// (POST /api/tasks)
	CreateTask(ctx echo.Context) error
	// get all tags
	// (GET /api/tasks/tags)
	GetTags(ctx echo.Context) error
	// delete task
	// (DELETE /api/tasks/{id})
	DeleteTask(ctx echo.Context, id int) error
	// get task
	// (GET /api/tasks/{id})
	GetTask(ctx echo.Context, id int) error
	// update task
	// (PUT /api/tasks/{id})
	UpdateTask(ctx echo.Context, id int) error
	// get user
	// (GET /api/user/{uid})
	GetUserByUID(ctx echo.Context, uid int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetGroups converts echo context to params.
func (w *ServerInterfaceWrapper) GetGroups(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGroups(ctx)
	return err
}

// CreateGroup converts echo context to params.
func (w *ServerInterfaceWrapper) CreateGroup(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateGroup(ctx)
	return err
}

// DeleteGroup converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteGroup(ctx, id)
	return err
}

// GetGroup converts echo context to params.
func (w *ServerInterfaceWrapper) GetGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGroup(ctx, id)
	return err
}

// UpdateGroup converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateGroup(ctx, id)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// Signup converts echo context to params.
func (w *ServerInterfaceWrapper) Signup(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Signup(ctx)
	return err
}

// GetTasks converts echo context to params.
func (w *ServerInterfaceWrapper) GetTasks(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTasks(ctx)
	return err
}

// CreateTask converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTask(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTask(ctx)
	return err
}

// GetTags converts echo context to params.
func (w *ServerInterfaceWrapper) GetTags(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTags(ctx)
	return err
}

// DeleteTask converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTask(ctx, id)
	return err
}

// GetTask converts echo context to params.
func (w *ServerInterfaceWrapper) GetTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTask(ctx, id)
	return err
}

// UpdateTask converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTask(ctx, id)
	return err
}

// GetUserByUID converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserByUID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "uid" -------------
	var uid int

	err = runtime.BindStyledParameterWithOptions("simple", "uid", ctx.Param("uid"), &uid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter uid: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserByUID(ctx, uid)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/groups", wrapper.GetGroups)
	router.POST(baseURL+"/api/groups", wrapper.CreateGroup)
	router.DELETE(baseURL+"/api/groups/:id", wrapper.DeleteGroup)
	router.GET(baseURL+"/api/groups/:id", wrapper.GetGroup)
	router.PUT(baseURL+"/api/groups/:id", wrapper.UpdateGroup)
	router.POST(baseURL+"/api/login", wrapper.Login)
	router.GET(baseURL+"/api/me", wrapper.GetCurrentUser)
	router.POST(baseURL+"/api/signup", wrapper.Signup)
	router.GET(baseURL+"/api/tasks", wrapper.GetTasks)
	router.POST(baseURL+"/api/tasks", wrapper.CreateTask)
	router.GET(baseURL+"/api/tasks/tags", wrapper.GetTags)
	router.DELETE(baseURL+"/api/tasks/:id", wrapper.DeleteTask)
	router.GET(baseURL+"/api/tasks/:id", wrapper.GetTask)
	router.PUT(baseURL+"/api/tasks/:id", wrapper.UpdateTask)
	router.GET(baseURL+"/api/user/:uid", wrapper.GetUserByUID)

}
